name: docker_latex
on: [push]
jobs:
  paper:
    runs-on: ubuntu-latest
    container: 
      image: texlive/texlive
    steps:
    - name: Compile Latex
      run: latexmk -pdflatex=xelatex -pdf master.tex
    - name: move
      run: mkdir -p github_artifacts && mv ${{ env.DIR }}/${{ env.FILE }}.pdf ./github_artifacts/
    - name: Upload pdf as artifact
      uses: actions/upload-artifact@v2
      
      
  deploy:
    # Edit here if compiling multiple papers
    needs: [paper]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: github_artifacts
      - name: move
        run: mkdir -p github_deploy && mv github_artifacts/*/* github_deploy
      - name: deploy on orphan branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./github_deploy
          publish_branch: build
          force_orphan: true
